# Generated by Django 3.1.1 on 2020-12-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('day', models.CharField(max_length=20)),
                ('startTime', models.CharField(max_length=20)),
                ('endTime', models.CharField(max_length=20)),
                ('details', models.CharField(max_length=100)),
            ],
        ),
    ]
